name: Panner
author: lorenzo.stanco
category: Interface
tags: [pan, panning, image, scrolling, scroll]
demo: http://www.lorenzostanco.com/demos/Panner/Demo.html
docs: https://github.com/lorenzos/Panner#docs
current: 0.2
sources:
  - "Source/Panner.js"